### ISSUE TITLE
DemandsValidator error for Pulverized Coal

### ISSUE THREAD

**Issue by dbantje** [polca/pathways#8]
Hi!

I'm running pathways with datapackages created with the "pathways" branch of premise (the SSP2-NPi scenario).

When I include the "Coal PC" variable, I get the following error:

```
multiprocessing.pool.RemoteTraceback: 
"""
Traceback (most recent call last):
  File "/home/davidba/.conda/envs/premise-pathways/lib/python3.11/multiprocessing/pool.py", line 125, in worker
    result = (True, func(*args, **kwds))
                    ^^^^^^^^^^^^^^^^^^^
  File "/home/davidba/.conda/envs/premise-pathways/lib/python3.11/multiprocessing/pool.py", line 48, in mapstar
    return list(map(*args))
           ^^^^^^^^^^^^^^^^
  File "/p/tmp/davidba/pathways/pathways/pathways/lca.py", line 632, in _calculate_year
    lca = bc.MultiLCA(
          ^^^^^^^^^^^^
  File "/home/davidba/.conda/envs/premise-pathways/lib/python3.11/site-packages/bw2calc/multi_lca.py", line 93, in __init__
    DemandsValidator(demands=demands)
  File "/home/davidba/.conda/envs/premise-pathways/lib/python3.11/site-packages/pydantic/main.py", line 212, in __init__
    validated_self = self.__pydantic_validator__.validate_python(data, self_instance=self)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
pydantic_core._pydantic_core.ValidationError: 1 validation error for DemandsValidator
demands.Coal PC.None.[key]
  Input should be a valid integer [type=int_type, input_value=None, input_type=NoneType]
    For further information visit https://errors.pydantic.dev/2.9/v/int_type
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/p/tmp/davidba/pathways/testing/run_pathways.py", line 37, in <module>
    p.calculate(
  File "/p/tmp/davidba/pathways/pathways/pathways/pathways.py", line 478, in calculate
    years, p.map(_calculate_year, args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/davidba/.conda/envs/premise-pathways/lib/python3.11/multiprocessing/pool.py", line 367, in map
    return self._map_async(func, iterable, mapstar, chunksize).get()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/davidba/.conda/envs/premise-pathways/lib/python3.11/multiprocessing/pool.py", line 774, in get
    raise self._value
pydantic_core._pydantic_core.ValidationError: 1 validation error for DemandsValidator
demands.Coal PC.None.[key]
  Input should be a valid integer [type=int_type, input_value=None, input_type=NoneType]
    For further information visit https://errors.pydantic.dev/2.9/v/int_type
srun: error: csp14c02: task 0: Exited with exit code 1
```

From the logfile:
```
2024-11-18 12:16:31 - INFO - lca - Functional unit: Coal PC, demand: {None: 163177636500.0}. Details: {'id': None, 'demand': 163177636500.0, 'fu': {None: 163177636500.0}, 'dataset': ('electricity production, hard coal, conventional', 'electricity, high voltage', 'kilowatt hour', 'CAZ'), 'unit vector': array(2.778e+11)}
```
It seems like some mapping error, but I'm having trouble identifying the source of the error. Any ideas?

Thanks!

**Comment by romainsacchi** [comment]
It seems the `.id` is missing. I'll try to have a look at it.
Can you paste the script you ran with `premise` and `pathways`, to reproduce this?

**Comment by dbantje** [comment]
This is the premise script:

```
from premise import *
import bw2data as bd

ei_version = "3.10"
bd.projects.set_current("pathways_testing_{}".format(ei_version))

scenarios=[
    {"model": "remind", "pathway": "SSP2-NPi", }
]

for scenario in scenarios:

    ndb = PathwaysDataPackage(
        scenarios=[
            scenario,
        ],
        #years=[
        #    2020, 
            #2050
        #],
        years=[2020, 2030, 2050],
        source_db="ecoinvent-3.10-cutoff", # <-- name of the database in the BW2 project. Must be a string.
        source_version=ei_version, # <-- version of ecoinvent. Can be "3.5", "3.6", "3.7" or "3.8". Must be a string.
        key="tUePmX_S5B8ieZkkM7WUU2CnO8SmShwmAeWK9x2rTFo=",
        use_absolute_efficiency=True,
        biosphere_name="ecoinvent-3.10-biosphere"
    )
    
    ndb.create_datapackage()
```

And the pathways script:
```

from pathways import Pathways
import datetime

p = Pathways(datapackage="pathways_2024-10-22.zip")

electricity_vars = [
    'Biomass CHP',
    'Biomass IGCC',
    'Biomass IGCC CCS',
    'Coal CHP',
    'Coal IGCC',
    'Coal IGCC CCS',
    'Coal PC',
    'Coal PC CCS',
    'Gas CC',
    'Gas CC CCS',
    'Gas CHP',
    'Gas OC',
    'Geothermal',
    'Hydro',
    'Nuclear',
    'Oil ST',
    'Solar CSP',
    'Solar PV Centralized',
    'Storage, Hydrogen',
    'Wind Offshore',
    'Wind Onshore'
]

# SE_vars = [k for k, ddict in p.mapping.items() if ddict["scenario variable"].startswith("SE")]
# SE_vars_noPC = [v for v in SE_vars if not "Coal PC" in v]

recipe2016_methods = [m for m in p.lcia_methods if m.startswith("ReCiPe 2016 v1.03, midpoint (H) - ")]
# EF_methods = [m for m in p.lcia_methods if m.startswith("EF v3.1 - ")]

p.calculate(
    methods=recipe2016_methods,
    scenarios=[
        "SSP2-NPi",
        #"SSP2-RCP19",
    ],
    variables=electricity_vars,
    years=[
        2020,
        2030,
        2050
    ],
    multiprocessing=True,
    use_distributions=0,
)

p.export_results()
```

**Comment by dbantje** [comment]
Found the root of this issue: `Coal PC` maps to

```
 'Coal PC': {'dataset': [{'name': 'electricity production, hard coal, conventional',
    'reference product': 'electricity, high voltage',
    'unit': 'kilowatt hour'},
   {'name': 'electricity production, lignite',
    'reference product': 'electricity, high voltage',
    'unit': 'kilowatt hour'},
   {'name': 'electricity production, hard coal',
    'reference product': 'electricity, high voltage',
    'unit': 'kilowatt hour'}],
  'scenario variable': 'SE|Electricity|Coal|++|Pulverised Coal w/o CC'},
```
and for the first candidate there is only one activity in the databases:

```
electricity production, hard coal, conventional;electricity, high voltage;kilowatt hour;ZA;14353
```
Might this be an outdated activity in ecoinvent 3.10?

In any case, something goes wrong when pathways tries to fetch the index for this (I guess at least for regions not including South Africa). For now, I'm just removing the first dataset in the Coal PC mapping.

Closing this issue, as I guess it's probably an upstream issue with premise which creates the mapping in the first place.
